#!/usr/bin/env bash
#
# RecruiterOS, one-shot server bootstrap.
# Run this ONCE on a fresh Hetzner Ubuntu server as root:
#
#   curl -fsSL https://raw.githubusercontent.com/neadusall/recruiteros/main/deploy.sh | bash
#
# It installs Docker, clones the repo, generates all secrets automatically,
# writes .env.production, and launches the app + Postgres + Caddy (auto-HTTPS).
# Re-running it later just pulls the latest code and redeploys (secrets are
# kept, the database volume is preserved).
set -euo pipefail

REPO="https://github.com/neadusall/recruiteros.git"
DIR="/opt/recruiteros"
DOMAIN="recruitersos.co"

say() { printf "\n\033[1;35m==> %s\033[0m\n" "$1"; }

# --- 1. dependencies ---
if ! command -v docker >/dev/null 2>&1; then
  say "Installing Docker"
  curl -fsSL https://get.docker.com | sh
fi
command -v git >/dev/null 2>&1 || { say "Installing git"; apt-get update -y && apt-get install -y git; }

# --- 2. firewall ---
if command -v ufw >/dev/null 2>&1; then
  say "Configuring firewall (SSH + HTTP + HTTPS)"
  ufw allow OpenSSH >/dev/null 2>&1 || true
  ufw allow 80 >/dev/null 2>&1 || true
  ufw allow 443 >/dev/null 2>&1 || true
  yes | ufw enable >/dev/null 2>&1 || true
fi

# --- 3. code ---
if [ -d "$DIR/.git" ]; then
  say "Updating existing checkout in $DIR"
  git -C "$DIR" pull --ff-only
else
  say "Cloning repo into $DIR"
  git clone "$REPO" "$DIR"
fi
cd "$DIR"

# --- 4. secrets / env (generated once, then preserved) ---
if [ ! -f .env.production ]; then
  say "Generating .env.production with fresh secrets"
  PGPW="$(openssl rand -hex 16)"
  SESSION="$(openssl rand -hex 32)"
  cat > .env.production <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Edit to add API keys.
RECRUITEROS_APP_URL=https://${DOMAIN}

# AI (optional until you add a key; sign-in works without it)
ANTHROPIC_API_KEY=
RECRUITEROS_LLM_MODEL=claude-sonnet-4-6

# Outreach + texting providers (optional until you go live with sending)
RECRUITEROS_OUTREACH_PROVIDER=internal
RECRUITEROS_OUTREACH_URL=
RECRUITEROS_OUTREACH_TOKEN=
RECRUITEROS_SMS_PROVIDER=telnyx
TELNYX_API_KEY=
TELNYX_MESSAGING_PROFILE_ID=
LOXO_API_KEY=

# Secrets (auto-generated, do not share)
RECRUITEROS_SESSION_SECRET=${SESSION}
POSTGRES_PASSWORD=${PGPW}
DATABASE_URL=postgres://recruiteros:${PGPW}@db:5432/recruiteros
EOF
  chmod 600 .env.production
else
  say "Keeping existing .env.production"
fi

# --- 5. launch ---
say "Building and starting containers (this takes a few minutes the first time)"
docker compose up -d --build

say "Done. Containers:"
docker compose ps

cat <<EOF

------------------------------------------------------------
RecruiterOS is starting.

1) Point DNS at this server in GoDaddy (recruitersos.co -> DNS):
     A   @     $(curl -s -4 ifconfig.me 2>/dev/null || echo YOUR_SERVER_IP)
     A   www   $(curl -s -4 ifconfig.me 2>/dev/null || echo YOUR_SERVER_IP)

2) Once DNS resolves, Caddy gets the HTTPS cert automatically.
   Watch it:   docker compose logs -f caddy

3) Then open:  https://${DOMAIN}/login.html

To add API keys later:  nano $DIR/.env.production  &&  docker compose up -d
------------------------------------------------------------
EOF
