#!/usr/bin/env bash
#
# RecruiterOS, one-shot server bootstrap.
# Run this ONCE on a fresh Hetzner Ubuntu server as root:
#
#   curl -fsSL https://raw.githubusercontent.com/neadusall/recruiteros/main/deploy.sh | bash
#
# It installs Docker, clones the repo, generates all secrets automatically,
# writes .env.production, and launches the app + Postgres + Caddy (auto-HTTPS).
# Re-running it later just pulls the latest code and redeploys (secrets are
# kept, the database volume is preserved).
set -euo pipefail

REPO="https://github.com/neadusall/recruiteros.git"
# Use the existing checkout if there is one (the live server is /opt/recruitersos);
# otherwise default to /opt/recruitersos for a fresh install. Overridable via env.
DIR="${RECRUITEROS_DIR:-}"
if [ -z "$DIR" ]; then
  if [ -d /opt/recruitersos/.git ]; then DIR="/opt/recruitersos"
  elif [ -d /opt/recruiteros/.git ]; then DIR="/opt/recruiteros"
  else DIR="/opt/recruitersos"; fi
fi
DOMAIN="recruitersos.co"

say() { printf "\n\033[1;35m==> %s\033[0m\n" "$1"; }

# --- 1. dependencies ---
if ! command -v docker >/dev/null 2>&1; then
  say "Installing Docker"
  curl -fsSL https://get.docker.com | sh
fi
command -v git >/dev/null 2>&1 || { say "Installing git"; apt-get update -y && apt-get install -y git; }

# --- 2. firewall ---
if command -v ufw >/dev/null 2>&1; then
  say "Configuring firewall (SSH + HTTP + HTTPS)"
  ufw allow OpenSSH >/dev/null 2>&1 || true
  ufw allow 80 >/dev/null 2>&1 || true
  ufw allow 443 >/dev/null 2>&1 || true
  yes | ufw enable >/dev/null 2>&1 || true
fi

# --- 3. code ---
if [ -d "$DIR/.git" ]; then
  say "Updating existing checkout in $DIR (hard reset to origin/main)"
  git -C "$DIR" fetch origin main --quiet
  git -C "$DIR" reset --hard origin/main
else
  say "Cloning repo into $DIR"
  git clone "$REPO" "$DIR"
fi
cd "$DIR"

# --- 3b. submodules (OS Text / taltxt lives in money-maker-sms) ---
say "Fetching submodules (OS Text app)"
git submodule sync --recursive || true
git submodule update --init --recursive

# --- 4. secrets / env (generated once, then preserved) ---
if [ ! -f .env.production ]; then
  say "Generating .env.production with fresh secrets"
  PGPW="$(openssl rand -hex 16)"
  SESSION="$(openssl rand -hex 32)"
  cat > .env.production <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Edit to add API keys.
RECRUITEROS_APP_URL=https://${DOMAIN}

# AI (optional until you add a key; sign-in works without it)
ANTHROPIC_API_KEY=
RECRUITEROS_LLM_MODEL=claude-sonnet-4-6

# Outreach: 'self' = our own in-backend bridge (work runs in the Chrome
# extension, coordinated here, no third party). 'unipile' for the hosted API.
RECRUITEROS_OUTREACH_PROVIDER=self
RECRUITEROS_OUTREACH_URL=
RECRUITEROS_OUTREACH_TOKEN=
RECRUITEROS_SMS_PROVIDER=telnyx
TELNYX_API_KEY=
TELNYX_MESSAGING_PROFILE_ID=
LOXO_API_KEY=

# Secrets (auto-generated, do not share)
RECRUITEROS_SESSION_SECRET=${SESSION}
POSTGRES_PASSWORD=${PGPW}
DATABASE_URL=postgres://recruiteros:${PGPW}@db:5432/recruiteros
EOF
  chmod 600 .env.production
else
  say "Keeping existing .env.production"
fi

# --- 4b. OS Text (taltxt) env (scaffolded once with generated secrets) ---
# taltxt is a separate app with its own keys (Neon, Telnyx, SMTP, QStash,
# Anthropic). We can auto-generate its session secrets and URLs; the rest must
# be filled in by hand. The container runs without them — features that need a
# given key simply stay off until you add it. See taltxt.env.example.
if [ -d money-maker-sms ] && [ ! -f money-maker-sms/.env.production ]; then
  say "Scaffolding money-maker-sms/.env.production (fill in the API keys after)"
  TX_AUTH="$(openssl rand -base64 32)"
  TX_ACCESS="$(openssl rand -hex 24)"
  # taltxt reuses the shared `db` Postgres (its own `taltxt` database), so it
  # connects with the same password recruiteros generated above.
  TX_PGPW="$(grep -E '^POSTGRES_PASSWORD=' .env.production | head -1 | cut -d= -f2-)"
  cat > money-maker-sms/.env.production <<EOF
# OS Text (taltxt) — generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Fill in the API keys below, then: docker compose up -d --build taltxt

# Public URL (the subdomain Caddy serves taltxt on). Used for auth callbacks,
# QStash webhook targets, and the instant-access link.
AUTH_URL=https://taltxt.recruitersos.co
PUBLIC_APP_URL=https://taltxt.recruitersos.co
AUTH_TRUST_HOST=true
NODE_ENV=production

# Auth (auto-generated; do not share)
AUTH_SECRET=${TX_AUTH}
ACCESS_TOKEN=${TX_ACCESS}
ACCESS_EMAIL=neadusall@gmail.com
ALLOWED_EMAILS=neadusall@gmail.com

# Database — the shared self-hosted Postgres (its own `taltxt` database).
# Run ./taltxt-db-setup.sh once to create the db + push the schema.
DATABASE_URL=postgres://recruiteros:${TX_PGPW}@db:5432/taltxt

# Email magic-link (Gmail SMTP recommended)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=

# Telnyx (SMS)
TELNYX_API_KEY=
TELNYX_MESSAGING_PROFILE_ID=
TELNYX_FROM_NUMBER=
TELNYX_PUBLIC_KEY=
TELNYX_MPS=1

# QStash (scheduled sends / drains)
QSTASH_TOKEN=
QSTASH_URL=https://qstash.upstash.io
QSTASH_CURRENT_SIGNING_KEY=
QSTASH_NEXT_SIGNING_KEY=

# AI
ANTHROPIC_API_KEY=

# Optional
APP_TIMEZONE=America/New_York
EOF
  chmod 600 money-maker-sms/.env.production
else
  [ -f money-maker-sms/.env.production ] && say "Keeping existing money-maker-sms/.env.production"
fi

# --- 5. launch ---
say "Building and starting containers (this takes a few minutes the first time)"
docker compose up -d --build

# --- 5b. OS Text DB (create the taltxt database + push its schema) ---
if [ -f "$DIR/taltxt-db-setup.sh" ] && [ -d money-maker-sms ]; then
  say "Setting up OS Text database (taltxt)"
  bash "$DIR/taltxt-db-setup.sh" || say "taltxt DB setup skipped/failed — re-run ./taltxt-db-setup.sh once .env.production is filled"
fi

# --- 6. auto-deploy watcher (idempotent; so future pushes go live on their own) ---
if [ -f "$DIR/install-auto-deploy.sh" ]; then
  say "Installing/refreshing the auto-deploy watcher"
  bash "$DIR/install-auto-deploy.sh" || true
fi

say "Done. Containers:"
docker compose ps

cat <<EOF

------------------------------------------------------------
RecruiterOS is starting.

1) Point DNS at this server in GoDaddy (recruitersos.co -> DNS):
     A   @       $(curl -s -4 ifconfig.me 2>/dev/null || echo YOUR_SERVER_IP)
     A   www     $(curl -s -4 ifconfig.me 2>/dev/null || echo YOUR_SERVER_IP)
     A   taltxt  $(curl -s -4 ifconfig.me 2>/dev/null || echo YOUR_SERVER_IP)   # OS Text

2) Once DNS resolves, Caddy gets the HTTPS cert automatically (apex + taltxt).
   Watch it:   docker compose logs -f caddy

3) Then open:  https://${DOMAIN}/login.html

To add API keys later:  nano $DIR/.env.production  &&  docker compose up -d

OS Text (taltxt) — fill in its keys (Neon DATABASE_URL is required):
   nano $DIR/money-maker-sms/.env.production  &&  docker compose up -d --build taltxt
   It then loads in the portal under the "OS Text" route, and at
   https://taltxt.${DOMAIN}
------------------------------------------------------------
EOF
