#!/usr/bin/env bash
#
# RecruitersOS, one-shot server bootstrap.
# Run this ONCE on a fresh Hetzner Ubuntu server as root:
#
#   curl -fsSL https://raw.githubusercontent.com/neadusall/recruiteros/main/deploy.sh | bash
#
# It installs Docker, clones the repo, generates all secrets automatically,
# writes .env.production, and launches the app + Postgres + Caddy (auto-HTTPS).
# Re-running it later just pulls the latest code and redeploys (secrets are
# kept, the database volume is preserved).
set -euo pipefail

REPO="https://github.com/neadusall/recruiteros.git"
# Use the existing checkout if there is one (the live server is /opt/recruitersos);
# otherwise default to /opt/recruitersos for a fresh install. Overridable via env.
DIR="${RECRUITEROS_DIR:-}"
if [ -z "$DIR" ]; then
  if [ -d /opt/recruitersos/.git ]; then DIR="/opt/recruitersos"
  elif [ -d /opt/recruiteros/.git ]; then DIR="/opt/recruiteros"
  else DIR="/opt/recruitersos"; fi
fi
DOMAIN="recruitersos.co"

say() { printf "\n\033[1;35m==> %s\033[0m\n" "$1"; }

# --- 1. dependencies ---
if ! command -v docker >/dev/null 2>&1; then
  say "Installing Docker"
  curl -fsSL https://get.docker.com | sh
fi
command -v git >/dev/null 2>&1 || { say "Installing git"; apt-get update -y && apt-get install -y git; }

# --- 2. firewall ---
if command -v ufw >/dev/null 2>&1; then
  say "Configuring firewall (SSH + HTTP + HTTPS)"
  ufw allow OpenSSH >/dev/null 2>&1 || true
  ufw allow 80 >/dev/null 2>&1 || true
  ufw allow 443 >/dev/null 2>&1 || true
  yes | ufw enable >/dev/null 2>&1 || true
fi

# --- 3. code ---
if [ -d "$DIR/.git" ]; then
  say "Updating existing checkout in $DIR (hard reset to origin/main)"
  git -C "$DIR" fetch origin main --quiet
  git -C "$DIR" reset --hard origin/main
else
  say "Cloning repo into $DIR"
  git clone "$REPO" "$DIR"
fi
cd "$DIR"

# --- 3b. submodules (OS Text lives in money-maker-sms) ---
say "Fetching submodules (OS Text app)"
git submodule sync --recursive || true
git submodule update --init --recursive

# --- 4. secrets / env (generated once, then preserved) ---
if [ ! -f .env.production ]; then
  say "Generating .env.production with fresh secrets"
  PGPW="$(openssl rand -hex 16)"
  SESSION="$(openssl rand -hex 32)"
  cat > .env.production <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Edit to add API keys.
RECRUITEROS_APP_URL=https://${DOMAIN}

# AI (optional until you add a key; sign-in works without it)
ANTHROPIC_API_KEY=
RECRUITEROS_LLM_MODEL=claude-sonnet-4-6

# Outreach: blank = auto (Unipile if its keys are set below, else 'self' = our own
# in-backend bridge via the Chrome extension). Force with: self | unipile | internal.
RECRUITEROS_OUTREACH_PROVIDER=
RECRUITEROS_OUTREACH_URL=
RECRUITEROS_OUTREACH_TOKEN=
# Unipile (hosted LinkedIn API). Set all three to run LinkedIn automation server-side.
# ACCOUNT_ID = the connected seat from GET https://<DSN>/api/v1/accounts -> items[].id
UNIPILE_DSN=
UNIPILE_API_KEY=
UNIPILE_ACCOUNT_ID=
UNIPILE_WEBHOOK_SECRET=
RECRUITEROS_SMS_PROVIDER=telnyx
TELNYX_API_KEY=
TELNYX_MESSAGING_PROFILE_ID=
LOXO_API_KEY=

# Secrets (auto-generated, do not share)
RECRUITEROS_SESSION_SECRET=${SESSION}
# POSTGRES_PASSWORD is for the SHARED Postgres that OS Text uses. The
# main app does NOT persist to Postgres — it snapshots accounts/sessions to the
# durable /data file volume (ROS_DATA_DIR=/data in compose), which survives every
# redeploy with no password to sync. Do NOT add a DATABASE_URL here: it would
# force the app back onto Postgres and re-introduce the "logged out on every
# deploy / account gone" bug.
POSTGRES_PASSWORD=${PGPW}
EOF
  chmod 600 .env.production
else
  say "Keeping existing .env.production"
fi

# --- 4b. OS Text env (scaffolded once with generated secrets) ---
# OS Text is a separate app with its own keys (Neon, Telnyx, SMTP, QStash,
# Anthropic). We can auto-generate its session secrets and URLs; the rest must
# be filled in by hand. The container runs without them — features that need a
# given key simply stay off until you add it. See ostext.env.example.
if [ -d money-maker-sms ] && [ ! -f money-maker-sms/.env.production ]; then
  say "Scaffolding money-maker-sms/.env.production (fill in the API keys after)"
  TX_AUTH="$(openssl rand -base64 32)"
  TX_ACCESS="$(openssl rand -hex 24)"
  # OS Text reuses the shared `db` Postgres (its own `taltxt` database), so it
  # connects with the same password recruiteros generated above.
  TX_PGPW="$(grep -E '^POSTGRES_PASSWORD=' .env.production | head -1 | cut -d= -f2-)"
  cat > money-maker-sms/.env.production <<EOF
# OS Text env: generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Fill in the API keys below, then: docker compose up -d --build taltxt

# Public URL. OS Text is served same-origin on the portal domain under
# /ostext-app (Caddy proxies it), so auth callbacks, QStash webhook targets,
# and the instant-access link all live on the portal host.
AUTH_URL=https://${DOMAIN}/ostext-app
PUBLIC_APP_URL=https://${DOMAIN}/ostext-app
AUTH_TRUST_HOST=true
NODE_ENV=production

# Auth (auto-generated; do not share)
AUTH_SECRET=${TX_AUTH}
ACCESS_TOKEN=${TX_ACCESS}
ACCESS_EMAIL=neadusall@gmail.com
ALLOWED_EMAILS=neadusall@gmail.com

# Database — Neon (managed Postgres). Paste your Neon connection string so the
# consolidated server reuses the EXISTING OS Text data with NO migration:
#   DATABASE_URL=postgres://<user>:<pass>@<host>.neon.tech/<db>?sslmode=require
# (Alternative: the shared local Postgres in this stack — then also run
#  ./ostext-db-setup.sh once to create the db + push schema:
#   DATABASE_URL=postgres://recruiteros:${TX_PGPW}@db:5432/taltxt )
DATABASE_URL=

# Email magic-link (Gmail SMTP recommended)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=

# Telnyx (SMS)
TELNYX_API_KEY=
TELNYX_MESSAGING_PROFILE_ID=
TELNYX_FROM_NUMBER=
TELNYX_PUBLIC_KEY=
TELNYX_MPS=1

# QStash (scheduled sends / drains)
QSTASH_TOKEN=
QSTASH_URL=https://qstash.upstash.io
QSTASH_CURRENT_SIGNING_KEY=
QSTASH_NEXT_SIGNING_KEY=

# AI
ANTHROPIC_API_KEY=

# Optional
APP_TIMEZONE=America/New_York
EOF
  chmod 600 money-maker-sms/.env.production
else
  [ -f money-maker-sms/.env.production ] && say "Keeping existing money-maker-sms/.env.production"
fi

# --- 4c. OS Text single sign-on: give the portal app the SAME instant-access
# token OS Text uses, so it can sign portal users straight in (no second login).
if [ -f money-maker-sms/.env.production ]; then
  TX_TOKEN="$(grep -E '^ACCESS_TOKEN=' money-maker-sms/.env.production | head -1 | cut -d= -f2-)"
  if [ -n "${TX_TOKEN:-}" ]; then
    say "Wiring OS Text single sign-on token into .env.production"
    if grep -q '^RECRUITEROS_OSTEXT_TOKEN=' .env.production; then
      sed -i "s|^RECRUITEROS_OSTEXT_TOKEN=.*|RECRUITEROS_OSTEXT_TOKEN=${TX_TOKEN}|" .env.production
    else
      echo "RECRUITEROS_OSTEXT_TOKEN=${TX_TOKEN}" >> .env.production
    fi
    # Same-origin embed: the portal reaches the engine at /ostext-app on its own
    # host, so no engine URL is scaffolded anymore. (RECRUITEROS_OSTEXT_URL is
    # legacy and ignored; RECRUITEROS_OSTEXT_DEV_URL exists for local dev only.)
  fi
fi

# --- 5. launch ---
say "Building and starting containers (this takes a few minutes the first time)"
docker compose up -d --build

# --- 5b. OS Text DB. Only needed for the LOCAL shared Postgres; with Neon the
# schema + data already live in the managed DB, so there's nothing to set up. ---
TX_DBURL="$(grep -E '^DATABASE_URL=' money-maker-sms/.env.production 2>/dev/null | head -1 | cut -d= -f2- || true)"
if [ -f "$DIR/ostext-db-setup.sh" ] && [ -d money-maker-sms ] && printf '%s' "${TX_DBURL:-}" | grep -q '@db:5432'; then
  say "Setting up the OS Text database on the shared local Postgres"
  bash "$DIR/ostext-db-setup.sh" || say "OS Text DB setup skipped/failed — re-run ./ostext-db-setup.sh once .env.production is filled"
else
  say "OS Text uses an external DB (Neon) — skipping local DB setup"
fi

# --- 6. auto-deploy watcher (idempotent; so future pushes go live on their own) ---
if [ -f "$DIR/install-auto-deploy.sh" ]; then
  say "Installing/refreshing the auto-deploy watcher"
  bash "$DIR/install-auto-deploy.sh" || true
fi

say "Done. Containers:"
docker compose ps

cat <<EOF

------------------------------------------------------------
RecruitersOS is starting.

1) Point DNS at this server in GoDaddy (recruitersos.co -> DNS):
     A   @       $(curl -s -4 ifconfig.me 2>/dev/null || echo YOUR_SERVER_IP)
     A   www     $(curl -s -4 ifconfig.me 2>/dev/null || echo YOUR_SERVER_IP)
     A   taltxt  $(curl -s -4 ifconfig.me 2>/dev/null || echo YOUR_SERVER_IP)   # legacy OS Text webhooks (optional on fresh installs)

2) Once DNS resolves, Caddy gets the HTTPS cert automatically.
   Watch it:   docker compose logs -f caddy

3) Then open:  https://${DOMAIN}/login.html

To add API keys later:  nano $DIR/.env.production  &&  docker compose up -d

OS Text: set DATABASE_URL to your Neon connection string (reuses the
existing data, no migration), then fill in Telnyx / QStash / Anthropic keys:
   nano $DIR/money-maker-sms/.env.production  &&  docker compose up -d --build taltxt
   It then loads in the portal under the "OS Text" route, served same-origin
   at https://${DOMAIN}/ostext-app (and on every white-label portal domain).
   (Once verified, you can safely decommission the old money-maker server.)
------------------------------------------------------------
EOF
