#!/usr/bin/env bash
#
# Set up OS Text (taltxt)'s database inside the shared `db` Postgres container:
#   1. create the `taltxt` database if it doesn't exist
#   2. push the taltxt Drizzle schema into it
#
# Safe to re-run. Run it once after first deploy, and again any time taltxt's
# schema changes (i.e. after bumping the money-maker-sms submodule). The stack
# must be up (docker compose up -d) so the `db` container is reachable.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

DB_NAME="taltxt"
DB_USER="recruiteros"

# The password the db + recruiteros app share (generated by deploy.sh).
PGPW="$(grep -E '^POSTGRES_PASSWORD=' .env.production 2>/dev/null | head -1 | cut -d= -f2- || true)"
if [ -z "${PGPW:-}" ]; then
  echo "ERROR: POSTGRES_PASSWORD not found in .env.production — run deploy.sh first." >&2
  exit 1
fi

echo "==> Ensuring database '$DB_NAME' exists"
if docker compose exec -T db psql -U "$DB_USER" -tAc \
     "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1; then
  echo "    already exists."
else
  docker compose exec -T db createdb -U "$DB_USER" "$DB_NAME"
  echo "    created."
fi

echo "==> Pushing taltxt schema (drizzle-kit push)"
# Use the taltxt image (it has Node) on the compose network; mount fresh source
# and install devDeps (drizzle-kit) into the mount. `db:5432` resolves on the net.
docker compose run --rm --entrypoint "" \
  -v "$DIR/money-maker-sms:/src" -w /src \
  -e DATABASE_URL="postgres://${DB_USER}:${PGPW}@db:5432/${DB_NAME}" \
  taltxt sh -lc "npm install --no-audit --no-fund && npm run db:push"

echo "==> Done. taltxt DB is ready (postgres://${DB_USER}:***@db:5432/${DB_NAME})."
