/**
 * RecruiterOS · Lume Search Partners export (raw rows)
 * The real people-export CSV, parsed to raw header→value rows. Fed through the
 * SAME importer (`rowsToInputs`) as a manual upload, so the warehouse shape is
 * identical to clicking "Import export" with this file. Source of truth for the
 * one-click seed at POST /api/dev/seed-data. Do not hand-edit — regenerate from
 * the CSV if it changes.
 */

export const LUME_ROWS: Array<Record<string, string>> = [
  {
    "Id": "6999360",
    "Name": "David Z. Steinberg, MBA",
    "Phone": "3475830315",
    "Email": "David@ascendracap.com",
    "Title": "Chief Investment Officer",
    "Company": "Ascendra Capital",
    "Location": "New York City Metropolitan Area",
    "City": "Flushing",
    "State": "NY",
    "Zip": "11354",
    "Country": "United States",
    "Owner": "Josh Gurin",
    "Created Date": "2025-10-29 13:21:37",
    "Source": "LinkedIn",
    "Recent Activity Date": "2026-06-08 12:23:19",
    "Type": "Contact",
    "LinkedIN": "https://www.linkedin.com/in/david-steinberg-mba",
    "Intake": "Ascendra Capital brings decades of investment management and\noperational experience in the healthcare, VC, lending, and real\nestate industries. Ascendra seeks to maximize risk adjusted\nreturns in VC, healthcare and real estate opportunities.",
    "Work Email": "David@ascendracap.com",
    "Personal Phone": "3475830315"
  },
  {
    "Id": "14315579",
    "Name": "Aaron Amaral",
    "Email": "aaron.amaral@fmr.com",
    "Title": "Senior Financial Analyst",
    "Company": "Fidelity Investments",
    "Location": "New York, United States",
    "State": "New York",
    "Country": "United States",
    "Owner": "Abigail Adler",
    "Created Date": "2026-02-11 09:38:32",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 10:14:00",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/aaron-amaral-cfa-caia-778977a8",
    "Intake": "Sr. Financial Analyst at Fidelity Investments",
    "Job Stage": "Outbound",
    "Work Email": "aaron.amaral@fmr.com"
  },
  {
    "Id": "14315656",
    "Name": "Cecily Petrarca",
    "Email": "cpetrarca@propellerindustries.com",
    "Title": "Financial Analyst",
    "Company": "Propeller Industries",
    "Location": "New York, United States",
    "State": "New York",
    "Country": "United States",
    "Owner": "Abigail Adler",
    "Created Date": "2026-02-11 09:48:57",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 10:14:23",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/cecily-petrarca-557491b5",
    "Intake": "Financial Associate Analyst at Mastercard under the Digital, Lab\nand Acceptance Solutions team.I am a financial analyst at\nMastercard supporting initiatives for Digital, Labs, and\nAcceptance. This role allows me to further my skills and learn as\nI work with on a number of projects. Being given the opportunity\nto work on traditional financial, sustainability, financial\ninclusion projects, and more allows me to apply the knowledge\nI've collected thus far in a way that advances the company's\nobjectives, helping people around the globe.",
    "Job Stage": "Outbound",
    "Work Email": "cpetrarca@propellerindustries.com"
  },
  {
    "Id": "14315679",
    "Name": "Jack Willard",
    "Email": "jack.willard@blackstone.com",
    "Title": "Senior Financial Analyst",
    "Company": "Fiserv",
    "Location": "New York, United States",
    "State": "New York",
    "Country": "United States",
    "Owner": "Abigail Adler",
    "Created Date": "2026-02-11 09:50:14",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 10:15:03",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/jack-willard-673b891b6",
    "Intake": "Sr. Financial Analyst at Fiserv",
    "Job Stage": "Outbound",
    "Work Email": "jack.willard@blackstone.com"
  },
  {
    "Id": "14355210",
    "Name": "DANIEL EREMITA",
    "Phone": "9143302043",
    "Email": "daneremita@yahoo.com",
    "Title": "Senior Accountant",
    "Company": "Louis Dreyfus Company",
    "Location": "CT",
    "City": "Stanford",
    "State": "CT",
    "Country": "United States",
    "Compensation": "$110,000.00 (Yearly) | $10,000.00 (Annual)",
    "Owner": "Noah Wilkowski",
    "Created Date": "2026-02-16 11:41:01",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 09:47:34",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/daniel-eremita-a0a563163",
    "Tags": "Corporate Accounting, Public",
    "Intake": "Intake Call:\n\n﻿6 years public out of college, moved to electrical contracting,\nthey limited his exposure to cost accounting and project based,\ndidnt have bigger picture, didnt mind the work just didnt like\nthe what capped at growth, now with a agricultural commodity\ntrading company, handles $200m.\n\nprefers heavier base.\n\ndaneremita@yahoo.com\n\nCandidate Summary:\n\nDan is an accounting professional with a strong blend of\nconstruction and corporate accounting experience. He currently\nserves as a Senior Accountant at Louis Dreyfus Company, leading\nmonth-end close and financial reporting activities for a $200M+\nNorth America business unit. Previously, he worked as a Project\nAccountant at Hellman Electric Corporation, where he managed WIP\nreporting, cost-to-complete analysis, billing, labor reporting,\nand contract cash flow management for large-scale construction\nprojects. Earlier in his career at Grassi & Co., he supported ERP\nmigrations including NetSuite and construction-related systems\nsuch as Viewpoint/Vista and Textura-related workflows, while also\nhandling outsourced accounting, financial reporting, and advisory\nengagements for middle-market clients.\n\nPost Interview:\n\nthinks went well, harder to read, highlighted senior title, cut\nchecks accounts payable, hat wearing role. refered to role as a\nsenior accountant, 7-4 in office 5x a week. has to think due to\nearlier start time. money wasn't discussed. doesn't like \"senior\naccountant title\" prefers a stronger title.",
    "Job Stage": "Interviewing",
    "Personal Email": "daneremita@yahoo.com",
    "Personal Phone": "9143302043"
  },
  {
    "Id": "14991546",
    "Name": "SHANI STEINER",
    "Phone": "516-732-8532",
    "Email": "bodnershoshana@gmail.com",
    "Title": "Office Administrator",
    "Company": "Lazer Marble & Granite / LMG Tile",
    "Location": "NY",
    "City": "Hewlett",
    "State": "NY",
    "Zip": "11557",
    "Country": "United States",
    "Owner": "Noah Wilkowski",
    "Created Date": "2026-03-31 13:54:06",
    "Source": "Other",
    "Recent Activity Date": "2026-06-08 12:23:52",
    "Type": "Candidate",
    "LinkedIN": "https://www.linkedin.com/in/shani-steiner/",
    "Intake": "Intake Call:\n\nessential runs the entire office/manager of all 3 locations.\nshani fix it, consulting for onboarding, she does it all.\n\nmanager at each location, COO, CEO (owner) each location has\noffice admin but she is the main admin that the owner leans on vs\nthe managers. She works closely with the COO, the manager isnt so\ninvolved, more of a sales person. shes essentially a chief of\nstaff. great with client relations.\n\nblown off for raise, no benefits. no yearly raise this year.",
    "Job Stage": "Screening",
    "Personal Email": "bodnershoshana@gmail.com",
    "Personal Phone": "516-732-8532"
  },
  {
    "Id": "19456242",
    "Name": "Coby Ackerman",
    "Email": "cobyackerman@gmail.com",
    "Title": "Tax/Audit Associate",
    "Company": "Brand Sonnenschine LLP - CPA's & Advisors",
    "Location": "Greater New York City Area",
    "City": "New York",
    "State": "NY",
    "Zip": "10155",
    "Country": "United States",
    "Owner": "Ariel Grosser",
    "Created Date": "2026-05-20 13:46:06",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 12:45:33",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/coby-ackerman-362371165",
    "Intake": "Tax/Audit Associate at Brand Sonnenschine LLPExperienced with a\ndemonstrated history of working in the professional training &\ncoaching industry. Skilled in Communication, Talking Points,\nCommunity Outreach, Engaging People, and Business Intelligence.\nGraduated Queens College Accounting and Political Science in\n2022.",
    "Job Stage": "Outbound",
    "Personal Email": "cobyackerman@gmail.com",
    "Work Email": "cobyackerman@bscpa.biz"
  },
  {
    "Id": "21216316",
    "Name": "COURTNEY LACKEY",
    "Phone": "817‑875‑0607",
    "Email": "c.m.lackey@icloud.com",
    "Title": "RCM Supervisor",
    "Company": "Vivo Infusion",
    "Location": "TX",
    "City": "Bedford",
    "State": "Texas",
    "Zip": "76022",
    "Country": "United States",
    "Compensation": "$76,000.00 (Yearly) | 5% (Annual)",
    "Owner": "Noah Wilkowski",
    "Created Date": "2026-05-28 12:06:33",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 09:55:43",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/courtney-lackey-8b1510118",
    "Tags": "Billing",
    "Intake": "* Texas, works remote, office in Colorado. not actively looking,\nenjoy vivo.\n* 10+ years of experience. likes working from home, 12 year old\ngirl going into junior high. 90's music.\n* experiencd with all insurances and medicaids, specialty\nmedications.\n* intake is her weakest area of knowledge, at vivo intake is its\nown department. she does overview meetings. manager above her.\nand director above that manager\n* built payment posting team.",
    "Job Stage": "Interviewing",
    "Personal Email": "c.m.lackey@icloud.com",
    "Personal Phone": "817‑875‑0607"
  },
  {
    "Id": "21248589",
    "Name": "Cristal Luna Marte",
    "Phone": "(607) 339-7050",
    "Email": "Cristal.luna504@gmail.com",
    "Title": "HR Assistant",
    "Company": "REACH Medical",
    "Location": "NJ",
    "State": "NJ",
    "Zip": "11354",
    "Country": "United States",
    "Compensation": "$62,000.00 (Yearly) | $8,000.00 (Annual)",
    "Owner": "Noah Wilkowski",
    "Created Date": "2026-06-02 10:54:34",
    "Source": "LinkedIn",
    "Recent Activity Date": "2026-06-08 11:57:30",
    "Type": "Candidate",
    "LinkedIN": "https://www.linkedin.com/in/cristal-luna-marte-934b363b4",
    "Tags": "HR, Hospital & Health Care",
    "Intake": "Intake Call:\n\n* she left reach after 5 years, started at front desk and worked\nup to HR.\n* wanted to work in NJ not NY.\n* most experience with maternity leave,\n* has other action\n\nCandidate Summary:\n\n﻿Cristal is an HR professional with progressive healthcare\nexperience. She lives in Newark NJ.\n\n* Supports full-cycle HR operations, including recruitment,\nonboarding, employee relations, policy administration, payroll\nprocessing, HR reporting, and employee communications for a\nmulti-department healthcare organization.\n* Experienced in healthcare compliance, conducting OMIG Medicaid\nExclusion checks, maintaining HIPAA-compliant HRIS records, and\nensuring adherence to federal, state, and organizational\nregulations.\n* Oversees payroll administration and HR documentation,\npartnering closely with leadership to maintain accurate employee\nrecords, compliance standards, and efficient HR processes.\nFamiliar with FMLA.\n* Strong healthcare operations background, with experience in\npatient access, front desk management, appointment scheduling,\nprior authorizations, provider coordination, and patient-facing\nadministrative support.\n* Additional behavioral health experience includes roles with\nLakeview Health Services, where she coordinated medication\nadministration, trained new hires, supported individuals with\nmental illness, and collaborated with multidisciplinary\nhealthcare teams.\n\nPost Interview:\n\n* convo flowed\n* 1500 employees\n* 20 minute convo\n* would move forward\n* has another interview tomorrow, had one last week. Tomorrow is\n2nd round in person, for a school with kids with disabilities HR\nassistant. Last week was HR coordinator additive. likes that one\nbetter because more $ (80K)",
    "Job Stage": "Submitted",
    "Personal Email": "Cristal.luna504@gmail.com",
    "Personal Phone": "(607) 339-7050"
  },
  {
    "Id": "21280029",
    "Name": "Casey Postema",
    "Title": "Franchise Support Lead",
    "Company": "Vital Care Infusion Services Related to search terms in your query",
    "Location": "Greater Wilmington Area",
    "City": "Wilmington",
    "State": "NC",
    "Zip": "28412",
    "Country": "United States",
    "Owner": "Ariel Grosser",
    "Created Date": "2026-06-08 00:32:50",
    "Source": "LinkedIn",
    "Recent Activity Date": "2026-06-08 00:32:53",
    "Type": "Candidate",
    "LinkedIN": "https://www.linkedin.com/in/casey-postema-21a768177",
    "Job Stage": "Longlist"
  },
  {
    "Id": "21280608",
    "Name": "Valeshia VanderVeen",
    "Title": "Vice President Revenue Cycle Related to search terms in your query Operations",
    "Company": "IVX Health Related to search terms in your query",
    "Location": "Greater Kalamazoo Area",
    "City": "Decatur",
    "State": "MI",
    "Zip": "49045",
    "Country": "United States",
    "Owner": "Ariel Grosser",
    "Created Date": "2026-06-08 09:46:49",
    "Source": "LinkedIn",
    "Recent Activity Date": "2026-06-08 09:46:52",
    "Type": "Candidate",
    "LinkedIN": "https://www.linkedin.com/in/valeshia-vanderveen-95048970",
    "Job Stage": "Longlist"
  },
  {
    "Id": "21280612",
    "Name": "Denise Delgado",
    "Title": "Senior Director",
    "Company": "OPTION HEALTH CARE INC",
    "Location": "San Antonio, Texas Metropolitan Area",
    "City": "San Antonio",
    "State": "TX",
    "Zip": "78222",
    "Country": "United States",
    "Owner": "Ariel Grosser",
    "Created Date": "2026-06-08 09:48:42",
    "Source": "LinkedIn",
    "Recent Activity Date": "2026-06-08 09:48:46",
    "Type": "Candidate",
    "LinkedIN": "https://www.linkedin.com/in/denise-delgado-245ba6169",
    "Job Stage": "Longlist"
  },
  {
    "Id": "21280616",
    "Name": "Ashlyn Bangert",
    "Title": "Associate Director of Referral Services",
    "Company": "LUX Infusion Related to search terms in your query",
    "Location": "Grand Prairie, Texas, United States",
    "City": "Grand Prairie",
    "State": "TX",
    "Zip": "75052",
    "Country": "United States",
    "Owner": "Ariel Grosser",
    "Created Date": "2026-06-08 09:50:22",
    "Source": "LinkedIn",
    "Recent Activity Date": "2026-06-08 09:50:26",
    "Type": "Candidate",
    "LinkedIN": "https://www.linkedin.com/in/ashlynbangert",
    "Job Stage": "Longlist"
  },
  {
    "Id": "21280622",
    "Name": "Julia Grinshpoon, MA",
    "Phone": "(347) 406-4397",
    "Email": "Jgrin904@gmail.com",
    "Title": "HR & Talent Development Manager",
    "Company": "Parker Health Group, NJ",
    "Location": "NJ",
    "City": "Minalapan",
    "State": "NJ",
    "Country": "United States",
    "Compensation": "$135,000.00 (Yearly)",
    "Owner": "Noah Wilkowski",
    "Created Date": "2026-06-08 09:52:52",
    "Source": "LinkedIn",
    "Recent Activity Date": "2026-06-08 12:39:33",
    "Type": "Candidate",
    "LinkedIN": "https://www.linkedin.com/in/julia-g-505141332/",
    "Tags": "HR, Sales, Staffing & Recruiting",
    "Intake": "Intake Call:\n\nLives in Manalapan, freehold mall.\n\n* melissa reports into her, Julia is people person, working with\npeople, employee relation, talent acquisition, training\nemployees. data analysis.\n* she thought she was building training sand performance she\nwould have people interactions.\n* commutes in currently\n* not available Wednesday",
    "Job Stage": "Submitted",
    "Personal Email": "Jgrin904@gmail.com",
    "Personal Phone": "(347) 406-4397"
  },
  {
    "Id": "21280634",
    "Name": "Stephanie B.",
    "Title": "Senior Authorizations Manager",
    "Company": "Valley Vital Care",
    "Location": "Ellabell, Georgia, United States",
    "City": "Ellabell",
    "State": "GA",
    "Zip": "31308",
    "Country": "United States",
    "Owner": "Ariel Grosser",
    "Created Date": "2026-06-08 09:54:54",
    "Source": "LinkedIn",
    "Recent Activity Date": "2026-06-08 09:55:02",
    "Type": "Candidate",
    "LinkedIN": "https://www.linkedin.com/in/stephanie-w-bergeron",
    "Job Stage": "Longlist"
  },
  {
    "Id": "21280799",
    "Name": "Rachel Hershberg",
    "Title": "Director Revenue Cycle",
    "Company": "WellSky",
    "Location": "Lakewood, New Jersey, United States",
    "City": "Lakewood",
    "State": "New Jersey",
    "Zip": "08701",
    "Country": "United States",
    "Owner": "Noah Wilkowski",
    "Created Date": "2026-06-08 10:35:31",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 12:08:18",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/rachel-hershberg-ab0a2632",
    "Tags": "Human Resource",
    "Intake": "Director Revenue Cycle Services - SNF",
    "Job Stage": "Outbound"
  },
  {
    "Id": "21280877",
    "Name": "Helen Brown",
    "Title": "Billing Manager",
    "Company": "Self Employed",
    "Location": "Brick, New Jersey, United States",
    "City": "Brick",
    "State": "NJ",
    "Zip": "08724",
    "Country": "United States",
    "Owner": "Noah Wilkowski",
    "Created Date": "2026-06-08 10:48:34",
    "Source": "LinkedIn",
    "Recent Activity Date": "2026-06-08 12:08:35",
    "Type": "Candidate",
    "LinkedIN": "https://www.linkedin.com/in/helen-brown-73719191",
    "Job Stage": "Outbound"
  },
  {
    "Id": "21281410",
    "Name": "David Botton",
    "Title": "Software Engineer",
    "Company": "Stealth Startup",
    "Location": "Fort Lauderdale, Florida, United States",
    "City": "Fort Lauderdale",
    "State": "Florida",
    "Zip": "33324",
    "Country": "United States",
    "Owner": "Noah Wilkowski",
    "Created Date": "2026-06-08 11:47:40",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 11:47:44",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/david-botton-3741b210",
    "Tags": "Medical Practice",
    "Intake": "Rabbi, Doctor and EngineerI am a Rabbi, a Physician of Chinese\nMedicine, and I am a Software Engineer. I am an enthusiastic\nlearner and teacher.",
    "Job Stage": "Shortlist"
  },
  {
    "Id": "21281412",
    "Name": "Yuda B",
    "Title": "Software Engineer",
    "Company": "Millennium",
    "Location": "Miami, Florida, United States",
    "City": "Miami",
    "State": "Florida",
    "Zip": "33170",
    "Country": "United States",
    "Owner": "Noah Wilkowski",
    "Created Date": "2026-06-08 11:47:47",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 11:47:50",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/yudabogo",
    "Intake": "Software Engineer @ MillenniumAs a Software Engineer at\nMillennium, I contribute to the cloud infrastructure that powers\none of the world’s most sophisticated, multi-strategy investment\nplatforms. As part of the AWS Platform Team, I focus on driving\nscalability, security, and innovation in the firm’s use of cloud\ntechnologies to support its dynamic trading and analytics\ncapabilities. I am committed to excellence and continuous\nlearning, aiming to deliver optimal results and contribute to\nMillennium’s legacy of investment success.",
    "Job Stage": "Shortlist"
  },
  {
    "Id": "21281413",
    "Name": "Isaac Gutt",
    "Title": "Software Engineer",
    "Company": "Bank of America",
    "Location": "Miami, Florida, United States",
    "City": "Miami",
    "State": "Florida",
    "Zip": "33170",
    "Country": "United States",
    "Owner": "Noah Wilkowski",
    "Created Date": "2026-06-08 11:47:54",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 11:47:57",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/isaac-gutt-1755a2183",
    "Intake": "Software Engineer at Bank of America",
    "Job Stage": "Shortlist"
  },
  {
    "Id": "21281579",
    "Name": "Anthony Limani",
    "Title": "Lead Software Engineer",
    "Company": "WellStat",
    "Location": "Jacksonville, Florida, United States",
    "City": "Jacksonville",
    "State": "Florida",
    "Zip": "32227",
    "Country": "United States",
    "Owner": "Ariel Grosser",
    "Created Date": "2026-06-08 12:04:31",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 12:04:36",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/anthonylimani",
    "Intake": "Lead Software Engineer at WellStatI’m a Software Engineer with\nWellStat. Having originally started my professional career in a\ndifferent field, I’ve worked diligently to gain all the skills\nand knowledge I need to perform, such as AWS, Spring Boot, and\nReact.js, and I’ve been able to accumulate these skills at a very\nfast pace. I’m addicted to problem-solving, learning new\ntechnologies and skills, and always ready for a fresh challenge.\nI got my start as a Mechanical Engineer designing and testing\ncutting-edge technology, but I got the itch to pursue software\nengineering, so when the opportunity to indulge that at WellStat\ncame along, I happily shifted focus. As a Data Analyst for\nWellStat, I worked face-to-face with customers to train them how\nto use our energy management platform, understand their business\nneeds, and create reports and visualizations for them on our\nplatform. I also supported customers by training their buildings’\nOperating Engineers how to shed their electric load for utility\nDemand Response events, leaning on my Mechanical Engineering\nbackground. Eventually, I was able to transition roles and became\na Software Engineer at WellStat, where I assumed responsibility\nfor managing our legacy Sprint Boot/ application and managing\ncritical AWS infrastructure, learning those technologies from\nscratch at a very rapid pace. Since then, I have been using my\nprior experience in mechanical engineering and business knowledge\nto guide the migration and development of products to a new\nNode/React/Express application and its integration into our cloud\nenvironment, work that is ongoing. I look to continue my software\njourney by deepening my expertise in full stack engineering and\ncloud technologies and integrating these skills in\ninterdisciplinary projects. I also hope to gain experience with\ndata engineering and analytics with Python. When I’m not hard at\nwork, I enjoy following Formula 1 with my wife, cooking or\ngrilling, tinkering with my Raspberry Pi, and playing video\ngames. I'm also an avid fan of classic rock and metal. If you’re\ninterested to learn more, I’m happy to connect with you on\nLinkedIn!",
    "Job Stage": "Shortlist"
  },
  {
    "Id": "21281580",
    "Name": "Andrew Pendergast",
    "Title": "Senior Software Engineer",
    "Company": "Agilesol Inc.",
    "Location": "Lakeland, Florida, United States",
    "City": "Lakeland",
    "State": "Florida",
    "Zip": "33807",
    "Country": "United States",
    "Owner": "Ariel Grosser",
    "Created Date": "2026-06-08 12:04:35",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 12:04:38",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/andrew-pendergast-a45b73212",
    "Intake": "Experienced Senior Software Engineer (Full Stack Web and Cloud\nProfessional) with a demonstrated history of working in the\ne-commerce, travel, education, chemicals, and healthcare\nindustry. Skilled in DevOps, Jenkins, C#, JavaScript, React,\nDocker, Git, Team Foundation Server (TFS), Azure DevOps, and\nAmazon Web Services (AWS). Strong engineering professional with a\nBachelor's degree in Information Technology from Florida State\nUniversity. Over the last 7+ years, I have developed a wide range\nof websites using .Net Core, ASP.NET, MVC, Web API, React, and\nTypeScript.",
    "Job Stage": "Shortlist"
  },
  {
    "Id": "21281587",
    "Name": "Michael Shanker",
    "Title": "Senior Software Engineer",
    "Company": "Cisco Meraki",
    "Location": "West Palm Beach, Florida, United States",
    "City": "West Palm Beach",
    "State": "Florida",
    "Zip": "33412",
    "Country": "United States",
    "Owner": "Ariel Grosser",
    "Created Date": "2026-06-08 12:05:16",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 12:05:21",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/michael-shanker",
    "Tags": "Hospital & Health Care",
    "Intake": "Software Engineer at Cisco MerakiFormer Urgent Care Administrator\nand current Computer Science undergrad at Florida Atlantic\nUniversity graduating in December 2019.",
    "Job Stage": "Shortlist"
  },
  {
    "Id": "21281589",
    "Name": "Cameron Taghlabi",
    "Title": "Software Developer",
    "Company": "Availity",
    "Location": "Jacksonville, Florida, United States",
    "City": "Jacksonville",
    "State": "Florida",
    "Zip": "32227",
    "Country": "United States",
    "Owner": "Ariel Grosser",
    "Created Date": "2026-06-08 12:05:19",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 12:05:21",
    "Type": "Candidate",
    "LinkedIN": "https://www.linkedin.com/search/results/people/?keywords=Cameron+Taghlabi+Availity",
    "Job Stage": "Shortlist"
  },
  {
    "Id": "21281598",
    "Name": "Leonardo Maicelo",
    "Title": "Full Stack Developer",
    "Company": "Self-Employed Freelancer",
    "Location": "Gainesville, Florida, United States",
    "City": "Gainesville",
    "State": "Florida",
    "Zip": "32609",
    "Country": "United States",
    "Owner": "Ariel Grosser",
    "Created Date": "2026-06-08 12:05:36",
    "Source": "Loxo Source",
    "Recent Activity Date": "2026-06-08 12:05:40",
    "Type": "Candidate",
    "LinkedIN": "https://linkedin.com/in/leonardo-maicelo-763866212",
    "Intake": "Computer Science Graduate | Specializing in Scalable Web\nApplications | Proficient in Java, C++, JavaScript, and React\nFrameworks such as Next.jsWith a passion for creating seamless\ndigital experiences, my expertise spans through libraries and\nframeworks such as React.js and Next.js, as well as various\nprogramming languages such as Java, TypeScript, C++ and Python.\nNotably, my freelance projects have significantly improved client\nsales and engagement, showcasing my ability to deliver impactful\nresults. A fast learner and effective communicator, I excel in\nteam collaboration and continuous improvement. As a member of the\nSociety of Hispanic Professional Engineers, I have demonstrated\nleadership and mentorship, guiding peers and contributing to a\nvibrant professional community. Let's connect and explore how we\ncan collaborate to bring innovative solutions to life!",
    "Job Stage": "Shortlist"
  }
];
