/**
 * RecruiterOS · Signal Engine
 * The signal registry — the catalog of every hiring signal we detect.
 *
 * This is the canonical "framework of all hiring signals". Each entry describes one
 * detector: what it means, how strong it is, how fast it decays, and which source
 * kinds can produce it. The collector, scorer, and the public API all read from here,
 * so adding a signal is a single edit in this file plus (optionally) a connector that
 * emits it.
 *
 * Tuning guide:
 *   baseWeight     — direct hiring intent (a posted role, a WARN notice) is high;
 *                    soft proxies (web traffic, reviews) are low.
 *   halfLifeHours  — how long the signal stays actionable. Dated events (WARN, IPO)
 *                    decay slowly; availability flags (open_to_work) decay fast.
 */

import type { SignalDefinition, SignalType } from "./types";

/** One definition per SignalType. Order here is the default display order. */
export const SIGNAL_DEFINITIONS: readonly SignalDefinition[] = [
  /* ── Capital & growth (business-dev) ───────────────────────────── */
  {
    type: "funding_round",
    label: "Funding round",
    category: "capital",
    subject: "company",
    motion: "business_dev",
    rationale: "New capital means new headcount and a budget to fill it. Be first in the inbox the week the round is announced.",
    baseWeight: 0.82,
    halfLifeHours: 24 * 30,        // a raise stays relevant ~a month
    emittedBy: ["funding_db", "news", "gov_filing"],
    evidenceKeys: ["amountUsd", "stage", "investors", "announcedAt"],
  },
  {
    type: "ipo_or_s1",
    label: "IPO / S-1 filing",
    category: "capital",
    subject: "company",
    motion: "business_dev",
    rationale: "Public-company readiness triggers aggressive hiring across finance, legal, and engineering.",
    baseWeight: 0.78,
    halfLifeHours: 24 * 45,
    emittedBy: ["gov_filing", "funding_db", "news"],
    evidenceKeys: ["filingType", "exchange", "filedAt"],
  },
  {
    type: "acquisition",
    label: "Acquisition",
    category: "capital",
    subject: "company",
    motion: "business_dev",
    rationale: "Acquisitions create integration hiring and shake loose retention-risk talent at the same time.",
    baseWeight: 0.7,
    halfLifeHours: 24 * 30,
    emittedBy: ["news", "funding_db", "gov_filing"],
    evidenceKeys: ["acquirer", "target", "valuationUsd"],
  },
  {
    type: "merger",
    label: "Merger",
    category: "capital",
    subject: "company",
    motion: "business_dev",
    rationale: "Mergers reshuffle the org chart, creating redundancy on one side and new roles on the other.",
    baseWeight: 0.66,
    halfLifeHours: 24 * 30,
    emittedBy: ["news", "gov_filing"],
    evidenceKeys: ["parties", "closeDate"],
  },
  {
    type: "revenue_milestone",
    label: "Revenue milestone",
    category: "capital",
    subject: "company",
    motion: "business_dev",
    rationale: "An ARR or earnings beat signals capacity expansion and budget to grow the team.",
    baseWeight: 0.58,
    halfLifeHours: 24 * 21,
    emittedBy: ["news", "gov_filing"],
    evidenceKeys: ["metric", "value", "period"],
  },
  {
    type: "grant_or_contract",
    label: "Grant / contract win",
    category: "capital",
    subject: "company",
    motion: "business_dev",
    rationale: "A government grant or large contract must be staffed to deliver, often on a deadline.",
    baseWeight: 0.6,
    halfLifeHours: 24 * 30,
    emittedBy: ["gov_filing", "news"],
    evidenceKeys: ["amountUsd", "agency", "awardId"],
  },

  /* ── Hiring intent (strongest, most direct) ────────────────────── */
  {
    type: "job_posting",
    label: "New job posting",
    category: "hiring_intent",
    subject: "company",
    motion: "business_dev",
    rationale: "The most direct signal there is: a role is open right now and someone owns filling it.",
    baseWeight: 0.75,
    halfLifeHours: 24 * 21,
    emittedBy: ["job_board", "ats_public"],
    evidenceKeys: ["roleTitle", "function", "location", "postedAt", "applyUrl"],
  },
  {
    type: "hiring_velocity",
    label: "Hiring surge",
    category: "hiring_intent",
    subject: "company",
    motion: "business_dev",
    rationale: "A spike in posting cadence above the company's baseline means a team stretched past capacity.",
    baseWeight: 0.88,
    halfLifeHours: 24 * 14,
    emittedBy: ["job_board", "ats_public", "company_graph"],
    evidenceKeys: ["rolesPosted", "window", "baseline", "functions"],
  },
  {
    type: "job_repost",
    label: "Role reposted",
    category: "hiring_intent",
    subject: "company",
    motion: "business_dev",
    rationale: "A reposted role means the company is struggling to fill it — the warmest possible moment to offer help.",
    baseWeight: 0.8,
    halfLifeHours: 24 * 14,
    emittedBy: ["job_board", "ats_public"],
    evidenceKeys: ["roleTitle", "firstSeenAt", "repostCount"],
  },
  {
    type: "evergreen_role",
    label: "Long-open role",
    category: "hiring_intent",
    subject: "company",
    motion: "business_dev",
    rationale: "A role open beyond the typical fill window signals pipeline pain you can solve.",
    baseWeight: 0.64,
    halfLifeHours: 24 * 21,
    emittedBy: ["job_board", "ats_public"],
    evidenceKeys: ["roleTitle", "daysOpen", "applyUrl"],
  },
  {
    type: "headcount_growth",
    label: "Headcount growth",
    category: "hiring_intent",
    subject: "company",
    motion: "business_dev",
    rationale: "An observed jump in employee count confirms the company is actively scaling its team.",
    baseWeight: 0.6,
    halfLifeHours: 24 * 30,
    emittedBy: ["company_graph", "people_graph"],
    evidenceKeys: ["delta", "window", "department"],
  },
  {
    type: "careers_page_launch",
    label: "Careers page launched",
    category: "hiring_intent",
    subject: "company",
    motion: "business_dev",
    rationale: "A brand-new careers site or jobs subdomain means a company formalizing its hiring function.",
    baseWeight: 0.55,
    halfLifeHours: 24 * 30,
    emittedBy: ["company_graph"],
    evidenceKeys: ["url", "detectedAt"],
  },
  {
    type: "ats_detected",
    label: "ATS adopted",
    category: "hiring_intent",
    subject: "company",
    motion: "business_dev",
    rationale: "Adopting or switching an applicant tracking system means building a repeatable hiring engine.",
    baseWeight: 0.52,
    halfLifeHours: 24 * 30,
    emittedBy: ["company_graph", "ats_public"],
    evidenceKeys: ["atsName", "detectedAt"],
  },

  /* ── Leadership & org change ───────────────────────────────────── */
  {
    type: "exec_hire",
    label: "New exec",
    category: "leadership",
    subject: "company",
    motion: "business_dev",
    rationale: "A new VP or C-level leader rebuilds their org within ~90 days and chooses new vendors.",
    baseWeight: 0.8,
    halfLifeHours: 24 * 60,
    emittedBy: ["people_graph", "news"],
    evidenceKeys: ["personName", "title", "function", "startedAt", "previousCompany"],
  },
  {
    type: "exec_departure",
    label: "Exec departure",
    category: "leadership",
    subject: "company",
    motion: "business_dev",
    rationale: "A departing exec leaves a backfill to run and a team that may follow them out the door.",
    baseWeight: 0.6,
    halfLifeHours: 24 * 45,
    emittedBy: ["people_graph", "news"],
    evidenceKeys: ["personName", "title", "leftAt"],
  },
  {
    type: "department_head_change",
    label: "New function lead",
    category: "leadership",
    subject: "company",
    motion: "business_dev",
    rationale: "A new head of Eng, Sales, or Marketing almost always kicks off a team build-out.",
    baseWeight: 0.7,
    halfLifeHours: 24 * 60,
    emittedBy: ["people_graph", "news"],
    evidenceKeys: ["personName", "function", "startedAt"],
  },
  {
    type: "board_change",
    label: "Board change",
    category: "leadership",
    subject: "company",
    motion: "business_dev",
    rationale: "A new board member or chair signals a strategic shift that reshapes hiring priorities.",
    baseWeight: 0.45,
    halfLifeHours: 24 * 60,
    emittedBy: ["gov_filing", "news"],
    evidenceKeys: ["personName", "role", "announcedAt"],
  },

  /* ── Contraction (talent hits the market) ──────────────────────── */
  {
    type: "layoff",
    label: "Layoff",
    category: "contraction",
    subject: "company",
    motion: "recruiting",
    rationale: "Great talent hits the market in batches. Detect the reduction and reach the affected people first.",
    baseWeight: 0.85,
    halfLifeHours: 24 * 14,
    emittedBy: ["news", "gov_filing", "social"],
    evidenceKeys: ["reductionPct", "affectedCount", "functions", "announcedAt"],
  },
  {
    type: "warn_notice",
    label: "WARN notice",
    category: "contraction",
    subject: "company",
    motion: "recruiting",
    rationale: "An official WARN filing gives you a dated, precise list of who is being released and when.",
    baseWeight: 0.9,
    halfLifeHours: 24 * 30,        // dated event, useful through the effective date
    emittedBy: ["gov_filing"],
    evidenceKeys: ["affectedCount", "effectiveDate", "site", "state"],
  },
  {
    type: "office_closure",
    label: "Office closure",
    category: "contraction",
    subject: "company",
    motion: "recruiting",
    rationale: "A site shutdown releases a concentrated pool of local talent all at once.",
    baseWeight: 0.7,
    halfLifeHours: 24 * 21,
    emittedBy: ["news", "gov_filing"],
    evidenceKeys: ["site", "affectedCount", "effectiveDate"],
  },
  {
    type: "down_round",
    label: "Down round",
    category: "contraction",
    subject: "company",
    motion: "recruiting",
    rationale: "Distress financing raises flight risk among strong staff before any public layoff.",
    baseWeight: 0.55,
    halfLifeHours: 24 * 30,
    emittedBy: ["funding_db", "news"],
    evidenceKeys: ["valuationDeltaPct", "stage"],
  },
  {
    type: "bankruptcy",
    label: "Bankruptcy",
    category: "contraction",
    subject: "company",
    motion: "recruiting",
    rationale: "Ch.7/11 puts both talent and an entire client base into play at once.",
    baseWeight: 0.72,
    halfLifeHours: 24 * 30,
    emittedBy: ["gov_filing", "news"],
    evidenceKeys: ["chapter", "filedAt"],
  },

  /* ── Footprint & strategy ──────────────────────────────────────── */
  {
    type: "office_expansion",
    label: "Expansion",
    category: "footprint",
    subject: "company",
    motion: "business_dev",
    rationale: "A new office or relocation creates a greenfield local team that has to be built from scratch.",
    baseWeight: 0.66,
    halfLifeHours: 24 * 30,
    emittedBy: ["news", "company_graph"],
    evidenceKeys: ["location", "announcedAt", "plannedHeadcount"],
  },
  {
    type: "market_entry",
    label: "New market",
    category: "footprint",
    subject: "company",
    motion: "business_dev",
    rationale: "Entering a new country, region, or segment means hiring people who know that market.",
    baseWeight: 0.6,
    halfLifeHours: 24 * 30,
    emittedBy: ["news"],
    evidenceKeys: ["market", "announcedAt"],
  },
  {
    type: "product_launch",
    label: "Product launch",
    category: "footprint",
    subject: "company",
    motion: "business_dev",
    rationale: "A new product line needs a team to build it and a team to sell it.",
    baseWeight: 0.5,
    halfLifeHours: 24 * 21,
    emittedBy: ["news", "social"],
    evidenceKeys: ["product", "launchedAt"],
  },
  {
    type: "partnership",
    label: "Partnership",
    category: "footprint",
    subject: "company",
    motion: "business_dev",
    rationale: "A major partnership or channel deal often requires staffing up to deliver on it.",
    baseWeight: 0.42,
    halfLifeHours: 24 * 21,
    emittedBy: ["news"],
    evidenceKeys: ["partner", "announcedAt"],
  },
  {
    type: "tech_stack_change",
    label: "Tech adoption",
    category: "footprint",
    subject: "company",
    motion: "business_dev",
    rationale: "Adopting a new technology creates demand for specialists who know it.",
    baseWeight: 0.5,
    halfLifeHours: 24 * 45,
    emittedBy: ["company_graph"],
    evidenceKeys: ["technology", "detectedAt"],
  },
  {
    type: "intent_surge",
    label: "Intent surge",
    category: "footprint",
    subject: "company",
    motion: "business_dev",
    rationale: "A research/intent spike on hiring-adjacent topics flags a company about to act.",
    baseWeight: 0.48,
    halfLifeHours: 24 * 10,
    emittedBy: ["intent"],
    evidenceKeys: ["topic", "intentScore"],
  },
  {
    type: "web_traffic_surge",
    label: "Traffic surge",
    category: "footprint",
    subject: "company",
    motion: "business_dev",
    rationale: "A demand spike implies scale pressure that usually precedes hiring.",
    baseWeight: 0.38,
    halfLifeHours: 24 * 14,
    emittedBy: ["company_graph", "intent"],
    evidenceKeys: ["deltaPct", "window"],
  },
  {
    type: "review_velocity",
    label: "Review velocity",
    category: "footprint",
    subject: "company",
    motion: "business_dev",
    rationale: "A spike in employer reviews is an early tell of either fast growth or churn — both create roles.",
    baseWeight: 0.36,
    halfLifeHours: 24 * 21,
    emittedBy: ["company_graph", "social"],
    evidenceKeys: ["reviewDelta", "sentiment"],
  },

  /* ── People-side (availability → recruiting) ───────────────────── */
  {
    type: "open_to_work",
    label: "Open to work",
    category: "people",
    subject: "person",
    motion: "recruiting",
    rationale: "An explicit availability flag is the warmest candidate signal — and it cools fast.",
    baseWeight: 0.9,
    halfLifeHours: 48,             // hottest in the first two days
    emittedBy: ["people_graph", "social"],
    evidenceKeys: ["detectedAt", "openToTitles"],
  },
  {
    type: "tenure_milestone",
    label: "Tenure milestone",
    category: "people",
    subject: "person",
    motion: "recruiting",
    rationale: "The 3- and 4-year marks are when people quietly start looking.",
    baseWeight: 0.55,
    halfLifeHours: 24 * 60,
    emittedBy: ["people_graph"],
    evidenceKeys: ["years", "company"],
  },
  {
    type: "promotion_passed_over",
    label: "Title stagnation",
    category: "people",
    subject: "person",
    motion: "recruiting",
    rationale: "Quiet title stagnation while peers move up is a strong, under-watched flight-risk signal.",
    baseWeight: 0.5,
    halfLifeHours: 24 * 45,
    emittedBy: ["people_graph"],
    evidenceKeys: ["yearsInTitle", "peerMovement"],
  },
  {
    type: "employer_distress",
    label: "Employer distress",
    category: "people",
    subject: "person",
    motion: "recruiting",
    rationale: "When a person's employer hits a layoff, down round, or exec exit, that person becomes reachable.",
    baseWeight: 0.7,
    halfLifeHours: 24 * 21,
    emittedBy: ["people_graph", "news"],
    evidenceKeys: ["employer", "distressType", "sourceSignalId"],
  },
  {
    type: "layoff_affected",
    label: "Layoff-affected",
    category: "people",
    subject: "person",
    motion: "recruiting",
    rationale: "A person confirmed impacted by a reduction is on the market now — reach them before competitors.",
    baseWeight: 0.85,
    halfLifeHours: 24 * 14,
    emittedBy: ["people_graph", "social"],
    evidenceKeys: ["employer", "sourceSignalId"],
  },
  {
    type: "job_change",
    label: "Job change",
    category: "people",
    subject: "person",
    motion: "recruiting",
    rationale: "A recent job change is a poor time to pitch but a great time to map the network and nurture.",
    baseWeight: 0.3,
    halfLifeHours: 24 * 30,
    emittedBy: ["people_graph"],
    evidenceKeys: ["fromCompany", "toCompany", "changedAt"],
  },
  {
    type: "profile_update",
    label: "Profile refresh",
    category: "people",
    subject: "person",
    motion: "recruiting",
    rationale: "A headline or skills refresh often quietly precedes an active search.",
    baseWeight: 0.4,
    halfLifeHours: 24 * 14,
    emittedBy: ["people_graph"],
    evidenceKeys: ["fields", "updatedAt"],
  },
  {
    type: "activity_spike",
    label: "Activity spike",
    category: "people",
    subject: "person",
    motion: "recruiting",
    rationale: "A surge in posting, endorsements, or engagement shows momentum and openness to conversation.",
    baseWeight: 0.35,
    halfLifeHours: 24 * 10,
    emittedBy: ["people_graph", "social"],
    evidenceKeys: ["activityType", "delta"],
  },
  {
    type: "relocation",
    label: "Relocation",
    category: "people",
    subject: "person",
    motion: "recruiting",
    rationale: "Someone moving into your market just became locally available for the first time.",
    baseWeight: 0.45,
    halfLifeHours: 24 * 30,
    emittedBy: ["people_graph"],
    evidenceKeys: ["fromGeo", "toGeo"],
  },
  {
    type: "education_completion",
    label: "Graduation / cert",
    category: "people",
    subject: "person",
    motion: "recruiting",
    rationale: "Finishing a degree, bootcamp, or certification often means re-entering the job market.",
    baseWeight: 0.32,
    halfLifeHours: 24 * 45,
    emittedBy: ["people_graph"],
    evidenceKeys: ["program", "completedAt"],
  },
  {
    type: "contract_ending",
    label: "Contract ending",
    category: "people",
    subject: "person",
    motion: "recruiting",
    rationale: "A contractor or visa term winding down creates a precise, dated window of availability.",
    baseWeight: 0.5,
    halfLifeHours: 24 * 30,
    emittedBy: ["people_graph", "manual"],
    evidenceKeys: ["endsAt", "engagementType"],
  },
] as const;

/* ------------------------------------------------------------------ */
/* Lookups                                                             */
/* ------------------------------------------------------------------ */

const BY_TYPE: Map<SignalType, SignalDefinition> = new Map(
  SIGNAL_DEFINITIONS.map((d) => [d.type, d]),
);

/** Fetch the definition for a signal type. Throws on an unregistered type. */
export function getDefinition(type: SignalType): SignalDefinition {
  const def = BY_TYPE.get(type);
  if (!def) throw new Error(`Unregistered signal type: ${type}`);
  return def;
}

/** All signal types for a given motion (recruiting | business_dev). */
export function definitionsForMotion(motion: SignalDefinition["motion"]): SignalDefinition[] {
  return SIGNAL_DEFINITIONS.filter((d) => d.motion === motion);
}

/** All signal types in a category. */
export function definitionsInCategory(category: SignalDefinition["category"]): SignalDefinition[] {
  return SIGNAL_DEFINITIONS.filter((d) => d.category === category);
}

/** The catalog as a plain array, for the public "what we watch" API endpoint. */
export function catalog(): SignalDefinition[] {
  return [...SIGNAL_DEFINITIONS];
}
